In [13]:
import pandas as pd

In [14]:
pd.read_csv("/home/mpoladi/DSC180A-Capstone/DSC180A-Methodology-2/data/gene_expression_new.csv")

     Unnamed: 0        0         1
0             4  HG00096  0.101858
1             5  HG00097  0.078110
2             6  HG00099  0.048981
3             7  HG00100  0.118597
4             8  HG00101  0.004035
..          ...      ...       ...
457         461  NA20815  0.088509
458         462  NA20816  0.029204
459         463  NA20819  0.024423
460         464  NA20826  0.044816
461         465  NA20828  0.139186

[462 rows x 3 columns]